### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by LuisFilipePedroso** [sandstreamdev/react-swipeable-list#23] opened 2019-09-26 13:30 UTC
I tried to install it and I got the error that files doesn't not exit. So I went to the folder node_modules/@sandstreamdev/react-swipeable-list and I realised that the project was empty, just contains folders, but not the React app.

**Comment by LuisFilipePedroso** [comment] 2019-09-26 13:48
I tried to install using yarn and neither the @sandstreamdev folder appeared into node_modules folder.

**Comment by przemyslawzalewski** [comment] 2019-09-26 14:47
I can confirm the issue. It seems that the build result wasn't packaged and all the dist folder contents is gone:
https://diff.intrinsic.com/@sandstreamdev/react-swipeable-list/0.1.0/0.2.0

**Comment by marekrozmus** [comment] 2019-09-27 06:28
Fixed in release [0.2.1](https://github.com/sandstreamdev/react-swipeable-list/releases/tag/v0.2.1)
It looks like np does not build before publishing - my bad. We need to update prepublish configuration.

**Closed by marekrozmus** 2019-09-27 06:28 UTC

**Comment by jakubbogacz** [comment] 2019-09-27 06:33
@LuisFilipePedroso: Thank you for your report. Can you confirm if it is working for you now?

**Comment by LuisFilipePedroso** [comment] 2019-09-27 11:41
Hey there. I installed here using NPM and YARN and now I can install, but inside of the folder @sandstreamdev/react-swipeable-list just have the folder dist. Does not have a index.js file to import the files and then I can not import the component into my project.

**Comment by przemyslawzalewski** [comment] 2019-09-27 12:02
@LuisFilipePedroso Could you inspect how you import the component? It should use `main`/`browser`/`module` fields of `package.json` to load an appropriate file based on your environment. In the `dist` folder there should be `react-swipeable-list.cjs.js`, `react-swipeable-list.esm.js` and `react-swipeable-list.umd.js`.
As there is no top-level `index.js` file, please do not import from `@sandstreamdev/react-swipeable-list/index.js` but rather `@sandstreamdev/react-swipeable-list` to let node/other tools resolve it using the mentioned environment fields.
The basic example seems to work out of the box: https://codesandbox.io/embed/green-mountain-c27tu

**Comment by LuisFilipePedroso** [comment] 2019-09-27 13:11
@przemyslawzalewski sorry, I was importing the component in the wrong way, I fixed here and now is working correctly. Thank you.

**Comment by przemyslawzalewski** [comment] 2019-09-27 13:34
@LuisFilipePedroso No need to be sorry :) You're welcome!

**Comment by marekrozmus** [comment] 2019-09-30 10:46
@all-contributors please add LuisFilipePedroso for bug

**Comment by marekrozmus** [comment] 2019-09-30 10:57
@all-contributors please add przemyslawzalewski for maintenance
